services:
  - type: web
    name: langflow
    env: docker
    plan: free
    region: frankfurt
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
